[book]
authors = ["Vishnu Reddy"]
language = "en"
multilingual = false
src = "src"
title = "Tutorial"


[output.html]
additional-css = ["visualization.css"]
additional-js = ["helpers.js"]
mathjax-support = true